;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Mood.Eat",DevComment="")
+GameplayTagList=(Tag="Mood.Idle",DevComment="")
+GameplayTagList=(Tag="Mood.Joy",DevComment="")
+GameplayTagList=(Tag="Mood.Rest",DevComment="")
+GameplayTagList=(Tag="Mood.Work",DevComment="")
+GameplayTagList=(Tag="Resource.Eat",DevComment="")
+GameplayTagList=(Tag="Resource.Rest",DevComment="")
+GameplayTagList=(Tag="Resource.Work",DevComment="")
+GameplayTagList=(Tag="Stat.Energy",DevComment="")
+GameplayTagList=(Tag="Stat.Joy",DevComment="")
+GameplayTagList=(Tag="Stat.Satiety",DevComment="")

